### ISSUE TITLE
`python_requires='>=3.5,<3.7'` prohibits installation on Python 3.7.x

### ISSUE THREAD

**Issue by KaiRo-at** [cobraframework/cobra-hdwallet#1]
`setup.py` seems a bit contradictory: it contains `python_requires='>=3.5,<3.7'` which would make it seem that Python 3.7.x is not supported, but `"Programming Language :: Python :: 3.7"` in `classifiers` makes it seem that it is supported.
In any case, pip denies installation in 3.7.x due to the former rule, can that be changed?

**Comment by meherett** [comment]
Thanks @KaiRo-at,
 It's fixed on v0.3.1.
